ADD: Inventory system
ink-inc/MagicMittelalterGame pull request #103
Opened 2020-03-31 12:47 UTC by kosch104

2020-04-05 18:31 UTC, Thabb requested changes
Anything

2020-04-05 18:32 UTC, SimonSchreinermacher submitted a review, later dismissed

2020-04-05 18:32 UTC, Segelzwerg requested changes
too much

2020-04-05 18:35 UTC, Segelzwerg submitted a review, later dismissed

2020-04-05 18:37 UTC, kosch104 commented on Assets/Scripts/Database/DBTest.cs
> +
```suggestion
        dialogueLineDB1.AddData(new DialogueLine(1, "Hallo!", 2));
        dialogueLineDB1.AddData(new DialogueLine(2, "Ich bin ein Stein!", 3));
        dialogueLineDB1.AddData(new DialogueLine(3, "Schnauze, Stein!", 4));
        dialogueLineDB1.AddData(new DialogueLine(4, "Hallo Roboter!", 5));
        dialogueLineDB1.AddData(new DialogueLine(5, "Erzähl mir was!", 10));
        dialogueLineDB1.AddData(new DialogueLine(6, "Ich bin kein Roboter, ich bin ein Stein!", 6));
        dialogueLineDB1.AddData(new DialogueLine(7, "Sorry!", 8));
        dialogueLineDB1.AddData(new DialogueLine(8, "Ich bestehe auf Roboter.", 7));
        dialogueLineDB1.AddData(new DialogueLine(9, "Dann unterhalt dich halt mit dir selbst!", 4));
        dialogueLineDB1.AddData(new DialogueLine(10, "Ist ok...", 9));
        dialogueLineDB1.AddData(new DialogueLine(11, "Möchtest du was interessantes wissen?", 15));
        dialogueLineDB1.AddData(new DialogueLine(12, "Nein", 4));
        dialogueLineDB1.AddData(new DialogueLine(13, "Ja", 10));
        dialogueLineDB1.AddData(new DialogueLine(14, "Was willst du hören?", 11));
        dialogueLineDB1.AddData(new DialogueLine(15, "Einen Witz bitte.", 12));
        dialogueLineDB1.AddData(new DialogueLine(16, "Was cooles!", 13));
        dialogueLineDB1.AddData(new DialogueLine(17, "Etwas, das ich wieder vergessen will.", 14));
        dialogueLineDB1.AddData(new DialogueLine(18, "Deine Mutter!", 4));
        dialogueLineDB1.AddData(new DialogueLine(19, "Wer eine nukleare Explosion verursacht, wird in Deutschland mit einer Freiheitsstrafe bis zu fünf Jahren oder mit einer Geldstrafe bestraft.", 4));
        dialogueLineDB1.AddData(new DialogueLine(20, "Bei Giraffen uriniert das Weibchen vor der Paarung in den Mund des Männchens.", 4));
```

2020-04-07 10:31 UTC, Thabb approved these changes

2020-04-07 10:31 UTC, merged