Ai/arena
ink-inc/MagicMittelalterGame pull request #254
Opened 2020-04-28 20:03 UTC by Segelzwerg

## Summary
Adds an empty scene with walls that will become the Ai Arena.

## Feature

The main purpose of this is to test the cartograph. This is a lot easier with a small compact scene.

2020-04-28 20:04 UTC, Segelzwerg commented
Merge #248 before!

2020-04-29 12:37 UTC, iTitus requested changes
can you rename the new scene, so we know what it's for

2020-04-29 18:16 UTC, Segelzwerg commented
> can you rename the new scene, so we know what it's for

yes there was a bug in Unity, when renaming it, it deleted the scene content. Maybe it will work after reboot.

2020-04-29 21:38 UTC, iTitus approved these changes

2020-04-29 21:41 UTC, merged