ADD: Basic Doc for Theme Manager
ink-inc/MagicMittelalterGame pull request #266
Opened 2020-05-03 11:17 UTC by kosch104

The numbering in the tutorial doesn't work... I don't know why. Please fix if you know why 👍

2020-05-03 11:19 UTC, iTitus commented
If you count just write 1. 1. 1. 1. 1.

2020-05-06 16:41 UTC, Thabb commented
Isn't that for .md?
For adoc it would be:
. First
. Second
. Third

Or if you want to number captions use
:numbered:
above the captions.

2020-05-27 10:37 UTC, iTitus requested changes
try this

2020-05-27 10:37 UTC, iTitus commented on doc/developer_guide/Themes/index.adoc
> +image::images/Theme.png[Theme scriptable view]
```suggestion
image:images/Theme.png[Theme scriptable view]
```

2020-05-27 10:37 UTC, iTitus commented on doc/developer_guide/Themes/index.adoc
> +image::images/ThemeManager.png[ThemeManager attached to HUD-GameObject in Editor]
```suggestion
image:images/ThemeManager.png[ThemeManager attached to HUD-GameObject in Editor]
```

2020-05-27 10:37 UTC, iTitus commented on doc/developer_guide/Themes/index.adoc
> +image::images/ImageTarget.png[ImageTarget with color preview]
```suggestion
image:images/ImageTarget.png[ImageTarget with color preview]
```

2020-08-01 10:36 UTC, iTitus approved these changes

2021-01-02 16:12 UTC, merged