ADD: Player Healthbar
ink-inc/MagicMittelalterGame pull request #55
Opened 2020-03-24 17:24 UTC by SimonSchreinermacher

2020-03-24 19:24 UTC, Mimonsi requested changes

2020-03-24 19:24 UTC, Mimonsi commented on Assets/PlayerHealthbar.cs
> +
```suggestion
```

Can be removed

2020-03-24 19:24 UTC, Mimonsi commented on Assets/PlayerProperties.cs
> +    }
```suggestion
```

Can be removed

2020-03-24 19:24 UTC, Mimonsi commented on Assets/TestHealthUpdate.cs
> +    }
```suggestion
```

2020-03-24 19:29 UTC, Mimonsi submitted a review, later dismissed

2020-03-25 13:37 UTC, Thabb requested changes
Die Healthbar bitte in eine der unteren Ecken verschieben, damit sie nicht so störend mitten auf dem Bildschirm ist.
Und bitte eine Möglichkeit zum Testgelände hinzu fügen mit der es möglich ist die  Funktionalität der Healthbar (also füllen bzw. senken der Healthbar) auch zu testen.
Es gilt immer zu berücksichtigen, dass alles was wir implementieren auch spiel und testbar sein sollte. Schließlich programmieren wir dieses Spiel nicht nur für uns selbst.

2020-03-25 14:56 UTC, kosch104 commented
> 
> 
> Die Healthbar bitte in eine der unteren Ecken verschieben, damit sie nicht so störend mitten auf dem Bildschirm ist.
> Und bitte eine Möglichkeit zum Testgelände hinzu fügen mit der es möglich ist die Funktionalität der Healthbar (also füllen bzw. senken der Healthbar) auch zu testen.
> Es gilt immer zu berücksichtigen, dass alles was wir implementieren auch spiel und testbar sein sollte. Schließlich programmieren wir dieses Spiel nicht nur für uns selbst.

Ich finde das persönlich besser in der Mitte - können wir aber immernoch nach finalem Design entscheiden

2020-03-25 17:11 UTC, Thabb requested changes
Die Interactables bitte auf den Boden stellen.
Und den Interactable Text von "[E] to damage yourself" zu "[E] Damage yourself" ändern. Den anderen Text natürlich auch.
Und wenn du mich wirklich glücklich machen willst, dann mach das Heal-Prob noch Schwarz-Grün statt Schwarz-Blau :P

2020-03-25 17:56 UTC, Thabb approved these changes

2020-03-25 17:57 UTC, merged